### ISSUE TITLE
Connect to Sense Server

### ISSUE THREAD

**Issue by countnazgul** [mindspank/qsocks#1]
I've tried to connect to Sense server but reached a point where I'm getting "Unauthorized (403)" error. Is it possible to pass credentials somehow?

Thanks!
Stefan

**Comment by mindspank** [comment]
What's the authentication method on your server? Is the url correctly formatted, I.e make sure the slashes are correct.

When qsocks initializes it will do a GET request to the hub and if you have a active directory sso setup it will automatically sign you in (setting the correct cookie).

If you are using any other auth modules then windows there is no support for that right now.

**Comment by countnazgul** [comment]
AD is the authentication method. 
What do you mean by "slashes are correct"?

Is it possible to post an example?

**Comment by mindspank** [comment]
Ops, I forgot the most important thing *facepalm*
Qlik Sense has a whitelist to authorize which origins are allowed to talk websockets.

So you need to whitelist the extension origin in your proxy, origin should be 

haifjhcobciacleiahcdnndlgankbdoa

But verify that by going to your extensions page in Chrome and look for the ID of the extension, that will be your origin to enter into the whitelist list in QMC. In QS 1.1 you will find it in QMC > Virtual Proxies > [Your Proxy] > Advanced

**Comment by mindspank** [comment]
Btw, have you whitelisted your server in the proxy whitelist?
qsocks tries to connect over websockets so make sure your origin is in the list of approved hosts.

**Comment by mindspank** [comment]
Well. So to make a long confusion short I initially thought you were raising the issue on the chrome extension SenseIt and not qsocks itself. Very stupid off me. So anyways, disregard any previous communication.

This gist contains a sample on how to authenticate a user, grab a ticket and establish the connection to the QIX engine.

https://gist.github.com/mindspank/c623e3f0bcf448093feb

**Comment by countnazgul** [comment]
That works perfect! 
Thanks!

**Comment by mindspank** [comment]
I know it's still plenty of documentation missing. I will start making some updates, I did however push a new update which now does not force you to specify /app/3%transient in the host so just fyi.

If you do build something cool feel free to share as we are in desperate need of cool stuff to show off :)

**Comment by countnazgul** [comment]
A little late but finally managed to spend some time to start building something using qsocks.bundle.js - https://github.com/countnazgul/qlik-sense-chrome-devtools-extension
