### ISSUE TITLE
Open multiple apps?

### ISSUE THREAD

**Issue by countnazgul** [mindspank/qsocks#10]
Is it possible to open more than one app in single session? If 'yes' then is there any example?

**Comment by mindspank** [comment]
In a session, yes you can have multiple apps open. 
But you can only have a single app per websocket.

Here is a example on multiple connections. I usually keep a global connection around just in case
https://github.com/mindspank/qsocks/blob/master/examples/Global/connect-scoped-connections.js

**Comment by countnazgul** [comment]
It's wired. It works fine if i use simple html file. In Chrome extension/app the second connection always return "App already open". Which in my understanding means that im in the same scope. Need to read more ...

**Comment by mindspank** [comment]
If you are connecting against Desktop you can pass in a object literal with a appname property.
Connecting without a appname property will connect to a generic global session, so if you open a document in that session you can't open a different document or the same app again.


So something like,
```
var global = qsocks.Connect()
var App1 = qsocks.Connect({appname: 'App1.qvf'})
var App2 = qsocks.Connect({appname: 'App2.qvf'})
```

**Comment by countnazgul** [comment]
Yep that's the case. Just noticed that my config object don't have appname (its dynamic). Adding appname solved it. Thanks.
