### ISSUE TITLE
Close doc?

### ISSUE THREAD

**Issue by countnazgul** [mindspank/qsocks#12]
Is it possible to close a document? My idea is to open document, do some stuff with it, close it and open another one without the need to open new connection for each app. 

I can see that there is `app.close()` method in the documentation ( http://goo.gl/v6thWH ) but can't see something like it in qsocks.

**Comment by mindspank** [comment]
Ye thats for the Capabilities API.
You can't "close" a app currently, the only way is to close the entire socket and open a new one.

You can close the socket by accessing <context>.connection.ws.close()

-----Original Message-----

**Comment by countnazgul** [comment]
Yea that's my workaround. Just wanted to be sure that im not missing something.
Thanks!
