### ISSUE TITLE
remove the need to gyp-rebuild when npm installing this package

### ISSUE THREAD

**Issue by pouc** [mindspank/qsocks#14]
Hi Alex,

when installing your package, unless I'm mistaken, two dependencies need gyp-rebuild (bufferutil & utf-8-validate). This requires ms vs installed on windows machines and this is a dependency that cannot be met all the time.

If vs is not installed the npm install fails but it works!

This is thus not really an issue but for cosmetic purposes it could be good in a future version to find a way to solve this!

Cheers
Loic

**Comment by mindspank** [comment]
Currently ws depends on compiled binaries for the utf-8 support.
I'm keeping track of their progress and they also have open issues for it and expect to resolve it quite soon.
