### ISSUE TITLE
CreateSessionAppFromApp does not return qSessionAppId

### ISSUE THREAD

**Issue by rvaheldendaten** [mindspank/qsocks#17]
Hi!

According to the documentation "CreateSessionAppFromApp" returns a "qSessionAppID". I wasn't able to grap this property with qsocks, as currently only msg.qReturn is used.

I fixed this for me by changing the code to:
``
Global.prototype.createSessionAppFromApp = function(qSrcAppId) {
    var connection = this.connection;
    return this.connection.ask(this.handle, 'CreateSessionAppFromApp', arguments).then(function(msg) 
{
        return [ msg.qSessionAppId, connection.create(msg.qReturn)];
    });
};
``
Currently I'm not able the Qlik Sense Application with the 'qSessionAppID', but that's probably something that I need to discuss with Qlik support...

Thx,
Roland

**Comment by mindspank** [comment]
Ye I don't return the ID since (I believe) you won't be able to connect to it from an outside session.
You can get the ID (which is the same as qTitle for session apps) by calling getAppProperties() on the app handle.

**Comment by rvaheldendaten** [comment]
Thx for the fast response.
Exactly, I want to "change script+reload" the sessionapp, and then redirect the user to:
https://qliksenseserver/sense/app/<qSessionAppId>

Therefore I need the qSessionAppId; unfortunately I dont't get it to work anyway. I thought the redirect would stay in the same session, but it seems it behaves differently..
