### ISSUE TITLE
No way to pass client cert via pfx/passphrase

### ISSUE THREAD

**Issue by 16bytes** [mindspank/qsocks#24]
There does not appear to be a way to connect to a remote Qlik Engine API with a client ssl cert with the pfx/passphrase.

We could use cert/key, but that would require unpacking the pfx, which is an extra step and also less secure since the key would be in cleartext.

It appears that adding support would be as easy as:

    cfg.pfx = config.pfx;
    cfg.passphrase = config.passphrase;

When reading in the config, which will be passed onto the ws WebSocket constructor directly.

**Comment by mindspank** [comment]
Correct, I haven't added any pfx support as Qlik Sense will export the service certificates by default as .pem files but that would be easy enough to add.
