### ISSUE TITLE
Create multiple master measure

### ISSUE THREAD

**Issue by dauledk** [mindspank/qsocks#28]
Hi Alexander. 

Looking very much forward to use this awesome project. 
How would you solve the task if you needed to add many master measures to an app?

Brgds

**Comment by mindspank** [comment]
Hey,
Here is a example on how to create a measure https://github.com/mindspank/qsocks/blob/master/examples/Object/measure.js

That should serve as a good starting point and also shows you the properties that the client expects.

**Comment by goldbergjeffrey** [comment]
@dauledk, check out the Governed Metrics Service my team is working on here.  This solution will allow you to send multiple dimensions and measures to unpublished and published apps.  Configuration docs for the entire Governed Self-Service reference deployment should be up in a couple of days.  Have a look at the code here: [Governed Metrics Service](https://github.com/eapowertools/QSGovernedMetrics)

**Comment by mindspank** [comment]
@dauledk Feel free to join us on slack (http://qlikbranch-slack-invite.herokuapp.com/) also if you have more questions, you can expect more rapid response there
