### ISSUE TITLE
createSessionObject to retrieve a DimensionList

### ISSUE THREAD

**Issue by dauledk** [mindspank/qsocks#29]
Hi Alexander.

I'm trying to retrieve a list of all master dimensions. Currently I have the following: 
`.then(function (app) {
    
    return app.createSessionObject({
        "qInfo": {
            "qType": "DimensionList"
        },
        "qDimensionListDef": {
            "qType": "dimension",
            "qData": {
                "title": "/title",
                "tags": "/tags",
                "grouping": "/qDim/qGrouping",
                "info": "/qDimInfos"
            }
        }
    }).then(function (GenericObject) {
        return GenericObject.GetLayout().then(function (dimension_list) { 
            console.log(dimension_list);
        })
    });
})`

But I am not sure how to do this?

**Comment by dauledk** [comment]
I got it now.. 
`
.then(function (app) {
    
    var obj = {
        "qInfo": {
            "qType": "DimensionList"
        },
        "qDimensionListDef": {
            "qType": "dimension",
            "qData": {
                "title": "/title",
                "tags": "/tags",
                "grouping": "/qDim/qGrouping",
                "info": "/qDimInfos"
            }
        }
    };

    app.createSessionObject(obj).then(function (list) {
        list.getLayout().then(function (layout) {
            console.log(layout.qInfo)
        });
    });
});
`

**Comment by mindspank** [comment]
Ah correct, while the Engine API documentation on the Qlik help site will list methods in pascal case qsock will utilize lower camelcase to be more js-centric.

Qlik Help Docs: GetLayout()
Qsocks: getLayout()
