### ISSUE TITLE
app.getObject( elementid, id) vs app.getObject(id)

### ISSUE THREAD

**Issue by linyunfeng** [mindspank/qsocks#35]
Hi, 
The current getObject api in qsocks only take id and return the object data model. Is there anyway we can enhance it like standard js api with elementid as 1 param so the function can render the display? Or any other workaround we can use with existing api?

**Comment by mindspank** [comment]
Hey, qsocks is just a promise wrapper around the Engine API so it does not have client implementations such as charts or visuals. Then you probably want to use the Capabilities API instead
